/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:587859:
  appc.background(230);
} //_CODE_:window1:587859:

public void lumSliderChanged(GCustomSlider source, GEvent event) { //_CODE_:lumSlider:896245:
  int newLuminosity = lumSlider.getValueI();
  
  for( Lamp l : lamps )
    l.setLuminosity( newLuminosity );
  
  reshadeRoad();
    
} //_CODE_:lumSlider:896245:

public void heightSliderChanged(GCustomSlider source, GEvent event) { //_CODE_:heightSlider:215887:
  lampHeight = heightSlider.getValueI();
  
  for( Lamp l : lamps )
    l.setHeight( lampHeight );
    
  reshadeRoad();
    
} //_CODE_:heightSlider:215887:

public void addButtonClicked(GButton source, GEvent event) { //_CODE_:addButton:259859:
  if( numLamps < 15) {
    numLamps++;
    resetLamps();
    reshadeRoad();
  }
} //_CODE_:addButton:259859:

public void removeButtonClicked(GButton source, GEvent event) { //_CODE_:removeButton:875198:
  if( numLamps > 1 ) {
    numLamps--;
    resetLamps();
    reshadeRoad();
  }
} //_CODE_:removeButton:875198:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 240, 200, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  lumSlider = new GCustomSlider(window1, 12, 38, 160, 30, "grey_blue");
  lumSlider.setLimits(1500000, 0, 6000000);
  lumSlider.setNumberFormat(G4P.INTEGER, 0);
  lumSlider.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  lumSlider.setOpaque(true);
  lumSlider.addEventHandler(this, "lumSliderChanged");
  label1 = new GLabel(window1, 12, 10, 80, 20);
  label1.setText("Luminosity");
  label1.setOpaque(false);
  heightSlider = new GCustomSlider(window1, 11, 105, 160, 30, "grey_blue");
  heightSlider.setLimits(100, 40, 300);
  heightSlider.setNumberFormat(G4P.INTEGER, 0);
  heightSlider.setOpaque(false);
  heightSlider.addEventHandler(this, "heightSliderChanged");
  label2 = new GLabel(window1, 11, 78, 80, 20);
  label2.setText("Lamp height");
  label2.setOpaque(false);
  addButton = new GButton(window1, 10, 160, 80, 30);
  addButton.setText("Add lamp");
  addButton.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  addButton.addEventHandler(this, "addButtonClicked");
  removeButton = new GButton(window1, 110, 160, 80, 30);
  removeButton.setText("Remove lamp");
  removeButton.setLocalColorScheme(GCScheme.RED_SCHEME);
  removeButton.addEventHandler(this, "removeButtonClicked");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GCustomSlider lumSlider; 
GLabel label1; 
GCustomSlider heightSlider; 
GLabel label2; 
GButton addButton; 
GButton removeButton; 
